name = "TwoElectronTDDFT"
uuid = "f184ada9-02e0-483f-abae-e4618e095841"
authors = ["Kyle Stewart <kyle.b.stewart.gr@dartmouth.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
